[features]
seeds = false
skip-lint = false
[programs.devnet]
missions_game = "Fdsd3qotXNtvEY9mnYKe5iZGfQVf6UHBqxX2X5d4HWCj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/raider/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
